language: node_js
node_js:
  - "6.11.5"
before_script:
  - npm install
script:
  - npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: pages #assuming you want to deploy with Github Pages, keep this
  skip-cleanup: true
  github-token: $GITHUB_TOKEN #create this in Github settings, add it to Travis settings
  verbose: true
  local_dir: dist
  on:
    branch: master